name: Publish

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install Deno
        run: curl -fsSL https://deno.land/install.sh | sh
      - name: Run release script
        run: .deno/bin/deno task release
